export const REQUEST_HISTORY = 'REQUEST_HISTORY';
export const ADD_TO_HISTORY = 'ADD_TO_HISTORY';
export const RECEIVE_HISTORY = 'RECEIVE_HISTORY';
export const ERROR_RECEIVE_HISTORY = 'ERROR_RECEIVE_HISTORY';